pipeline {
    agent any

    stages {
        stage('Unit Tests _ Backend') {
            steps {
                dir('bugtracker-backend')
                    go test -v ./...
            }
        }
    }
}
